//
//  LFColor.h
//

#ifndef LFColor_h
#define LFColor_h

/**
 * 这个宏主要作用是生成一个颜色的（static inline）函数
 * 参数是一个颜色值的6位hex，如（000000），然后就可以LF_color_000000()调用
 */
#define LF_GENERATE_COLOR_STATIC_INLINE(hex) _LF_GENERATE_COLOR_STATIC_INLINE(hex)
#define _LF_GENERATE_COLOR_STATIC_INLINE(hex) \
UIKIT_STATIC_INLINE UIColor *LF_color_##hex() { \
return [UIColor colorWithHexString:@#hex]; \
}

LF_GENERATE_COLOR_STATIC_INLINE(ffffff)
LF_GENERATE_COLOR_STATIC_INLINE(e2e2e2)
LF_GENERATE_COLOR_STATIC_INLINE(ff8300)
LF_GENERATE_COLOR_STATIC_INLINE(2dc352)
LF_GENERATE_COLOR_STATIC_INLINE(FB4E10)
LF_GENERATE_COLOR_STATIC_INLINE(0080ff)
LF_GENERATE_COLOR_STATIC_INLINE(f6f6f6)
LF_GENERATE_COLOR_STATIC_INLINE(fd8917)
LF_GENERATE_COLOR_STATIC_INLINE(e6e6e6)
LF_GENERATE_COLOR_STATIC_INLINE(eeeeee)
LF_GENERATE_COLOR_STATIC_INLINE(666666)
LF_GENERATE_COLOR_STATIC_INLINE(333333)
LF_GENERATE_COLOR_STATIC_INLINE(454545)
LF_GENERATE_COLOR_STATIC_INLINE(3cb236)
LF_GENERATE_COLOR_STATIC_INLINE(ea1e1e)
LF_GENERATE_COLOR_STATIC_INLINE(b2b2b2)
LF_GENERATE_COLOR_STATIC_INLINE(3f3d3f)
LF_GENERATE_COLOR_STATIC_INLINE(3895f4)
LF_GENERATE_COLOR_STATIC_INLINE(efeff4)
LF_GENERATE_COLOR_STATIC_INLINE(14a6de)

#endif /* LFColor_h */
